/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/skill-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skill Nodes */
        get: operations["list_skill_nodes_api_skill_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skill-tree/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill Node */
        get: operations["get_skill_node_api_skill_tree__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exam Attempts */
        get: operations["list_exam_attempts_api_exam_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Exam */
        post: operations["start_exam_api_exam_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam State */
        get: operations["get_exam_state_api_exam__attempt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Question */
        post: operations["answer_question_api_exam__attempt_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Exam */
        post: operations["submit_exam_api_exam__attempt_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam Review */
        get: operations["get_exam_review_api_exam__attempt_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlternativeOut */
        AlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Is Correct */
            is_correct: boolean;
            /** Distractor Justification */
            distractor_justification?: string | null;
        };
        /** AnalyticsSummaryOut */
        AnalyticsSummaryOut: {
            /** Current Streak Days */
            current_streak_days: number;
            /** Total Questions Answered */
            total_questions_answered: number;
            /** Total Correct */
            total_correct: number;
            /** Overall Accuracy */
            overall_accuracy: number | null;
            /** Total Minutes Practiced */
            total_minutes_practiced: number;
            /** Daily */
            daily: components["schemas"]["DailyStat"][];
        };
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "in_progress" | "submitted" | "abandoned";
        /** DailyStat */
        DailyStat: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Questions Answered */
            questions_answered: number;
            /** Correct */
            correct: number;
            /** Accuracy */
            accuracy: number | null;
            /** Minutes Practiced */
            minutes_practiced: number;
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "facil" | "medio" | "dificil";
        /**
         * ExamAlternativeOut
         * @description Alternativa durante el examen: SIN is_correct ni
         *     distractor_justification. Esos datos solo se exponen después de
         *     submit (feature de Smart Feedback / autopsia del error).
         */
        ExamAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** ExamAnswerIn */
        ExamAnswerIn: {
            /** Question Id */
            question_id: number;
            /** Selected Alternative Id */
            selected_alternative_id?: number | null;
            /**
             * Time Spent Ms
             * @default 0
             */
            time_spent_ms: number;
        };
        /** ExamAnswerState */
        ExamAnswerState: {
            /** Selected Alternative Id */
            selected_alternative_id?: number | null;
            /**
             * Time Spent Ms
             * @default 0
             */
            time_spent_ms: number;
        };
        /** ExamAttemptSummary */
        ExamAttemptSummary: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            status: components["schemas"]["AttemptStatus"];
            /** Total Questions */
            total_questions: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
        };
        /** ExamQuestionOut */
        ExamQuestionOut: {
            /** Id */
            id: number;
            /** Skill Node Id */
            skill_node_id: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Image Url */
            image_url?: string | null;
            /** Alternatives */
            alternatives: components["schemas"]["ExamAlternativeOut"][];
        };
        /** ExamResultOut */
        ExamResultOut: {
            /** Attempt Id */
            attempt_id: number;
            status: components["schemas"]["AttemptStatus"];
            /** Total Questions */
            total_questions: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
        };
        /** ExamReviewOut */
        ExamReviewOut: {
            /** Attempt Id */
            attempt_id: number;
            status: components["schemas"]["AttemptStatus"];
            /** Questions */
            questions: components["schemas"]["ReviewQuestionOut"][];
            /** Node Diagnosis */
            node_diagnosis: components["schemas"]["NodeDiagnosisOut"][];
        };
        /** ExamStartOut */
        ExamStartOut: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            /** Questions */
            questions: components["schemas"]["ExamQuestionOut"][];
        };
        /** ExamStateOut */
        ExamStateOut: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            /** Questions */
            questions: components["schemas"]["ExamQuestionOut"][];
            status: components["schemas"]["AttemptStatus"];
            /** Answers */
            answers: {
                [key: string]: components["schemas"]["ExamAnswerState"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NodeDiagnosisOut */
        NodeDiagnosisOut: {
            /** Skill Node Id */
            skill_node_id: number;
            /** Skill Node Code */
            skill_node_code: string;
            /** Skill Node Name */
            skill_node_name: string;
            /** Axis */
            axis: string;
            /** Total */
            total: number;
            /** Correct */
            correct: number;
            /** Accuracy */
            accuracy: number;
        };
        /** QuestionOut */
        QuestionOut: {
            /** Id */
            id: number;
            /** Skill Node Id */
            skill_node_id: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Image Url */
            image_url?: string | null;
            /** Alternatives */
            alternatives: components["schemas"]["AlternativeOut"][];
        };
        /**
         * ReviewAlternativeOut
         * @description Alternativa en la revisión post-examen: SÍ incluye is_correct y
         *     distractor_justification — la autopsia del error.
         */
        ReviewAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Is Correct */
            is_correct: boolean;
            /** Distractor Justification */
            distractor_justification?: string | null;
            /** Selected */
            selected: boolean;
        };
        /** ReviewQuestionOut */
        ReviewQuestionOut: {
            /** Id */
            id: number;
            /** Stem */
            stem: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Skill Node Id */
            skill_node_id: number;
            /** Skill Node Code */
            skill_node_code: string;
            /** Skill Node Name */
            skill_node_name: string;
            /** Time Spent Ms */
            time_spent_ms: number;
            /** Answered Correctly */
            answered_correctly: boolean | null;
            /** Alternatives */
            alternatives: components["schemas"]["ReviewAlternativeOut"][];
        };
        /**
         * SkillAxis
         * @enum {string}
         */
        SkillAxis: "numeros" | "algebra" | "geometria" | "probabilidad";
        /** SkillNodeOut */
        SkillNodeOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            axis: components["schemas"]["SkillAxis"];
            /** Tier */
            tier: number;
            /** Unlock Threshold */
            unlock_threshold: number;
            /** Display Order */
            display_order: number;
            /**
             * Prerequisite Codes
             * @default []
             */
            prerequisite_codes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_skill_nodes_api_skill_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNodeOut"][];
                };
            };
        };
    };
    get_skill_node_api_skill_tree__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_questions_get: {
        parameters: {
            query?: {
                skill_node_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exam_attempts_api_exam_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttemptSummary"][];
                };
            };
        };
    };
    start_exam_api_exam_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamStartOut"];
                };
            };
        };
    };
    get_exam_state_api_exam__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_api_exam__attempt_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_exam_api_exam__attempt_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_review_api_exam__attempt_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummaryOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
