/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Config
         * @description La web consulta esto para saber si mostrar el botón de Google.
         */
        get: operations["auth_config_api_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login With Google */
        post: operations["login_with_google_api_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Siempre responde 204, exista o no el correo: no revela qué cuentas
         *     están registradas.
         */
        post: operations["forgot_password_api_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_auth_me_patch"];
        trace?: never;
    };
    "/api/skill-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skill Nodes */
        get: operations["list_skill_nodes_api_skill_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skill-tree/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommended Node */
        get: operations["get_recommended_node_api_skill_tree_recommended_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skill-tree/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill Node */
        get: operations["get_skill_node_api_skill_tree__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Questions
         * @description Nunca expone is_correct ni distractor_justification (ver
         *     QuestionSafeOut) — misma regla de integridad que el Modo Examen.
         */
        get: operations["list_questions_api_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Options
         * @description Ejes y disponibilidad del banco, para la pantalla de configuración.
         */
        get: operations["get_exam_options_api_exam_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/repaso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repaso
         * @description Sugerencia para el botón "Ensayo de repaso" en la config del ensayo.
         */
        get: operations["get_repaso_api_exam_repaso_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exam Attempts */
        get: operations["list_exam_attempts_api_exam_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Exam */
        post: operations["start_exam_api_exam_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam State */
        get: operations["get_exam_state_api_exam__attempt_id__get"];
        put?: never;
        post?: never;
        /** Delete Exam Attempt */
        delete: operations["delete_exam_attempt_api_exam__attempt_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Question */
        post: operations["answer_question_api_exam__attempt_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Exam */
        post: operations["submit_exam_api_exam__attempt_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Result
         * @description Mismo resumen que devuelve submit, para volver a abrir un ensayo pasado.
         */
        get: operations["get_exam_result_api_exam__attempt_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam Review */
        get: operations["get_exam_review_api_exam__attempt_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/{code}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice Questions */
        get: operations["get_practice_questions_api_practice__code__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/{code}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Practice Question */
        post: operations["answer_practice_question_api_practice__code__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Demo Questions
         * @description Preguntas de prueba SIN cuenta: pública, sin auth, sin persistir nada.
         *     Solo fácil/medio -- la demo busca enganchar, no frustrar en el primer
         *     contacto con la plataforma.
         */
        get: operations["get_demo_questions_api_demo_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grade Demo
         * @description Corrige la demo al vuelo, sin guardar ningún intento -- no hay usuario
         *     todavía, así que no hay dónde guardarlo.
         */
        post: operations["grade_demo_api_demo_grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlternativeSafeOut
         * @description Alternativa sin is_correct ni distractor_justification — para
         *     listados públicos/autenticados que no deben revelar la respuesta.
         */
        AlternativeSafeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** AnalyticsSummaryOut */
        AnalyticsSummaryOut: {
            /** Current Streak Days */
            current_streak_days: number;
            /** Total Questions Answered */
            total_questions_answered: number;
            /** Total Correct */
            total_correct: number;
            /** Overall Accuracy */
            overall_accuracy: number | null;
            /** Total Minutes Practiced */
            total_minutes_practiced: number;
            /** Daily */
            daily: components["schemas"]["DailyStat"][];
        };
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "in_progress" | "submitted" | "abandoned";
        /**
         * AuthConfigOut
         * @description Qué métodos de inicio de sesión están habilitados en este despliegue.
         */
        AuthConfigOut: {
            /** Google Enabled */
            google_enabled: boolean;
        };
        /**
         * AxisOptionOut
         * @description Un eje temático y cuántas preguntas hay disponibles en el banco.
         */
        AxisOptionOut: {
            /** Axis */
            axis: string;
            /** Label */
            label: string;
            /** Available */
            available: number;
        };
        /**
         * BreakdownItemOut
         * @description Desempeño agrupado por eje, nodo o dificultad.
         */
        BreakdownItemOut: {
            /** Name */
            name: string;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Omitted */
            omitted: number;
            /** Total */
            total: number;
            /** Percentage */
            percentage: number;
        };
        /** DailyStat */
        DailyStat: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Questions Answered */
            questions_answered: number;
            /** Correct */
            correct: number;
            /** Accuracy */
            accuracy: number | null;
            /** Minutes Practiced */
            minutes_practiced: number;
        };
        /**
         * DemoAlternativeOut
         * @description Sin is_correct: misma regla de integridad que el Modo Examen.
         */
        DemoAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** DemoAnswerIn */
        DemoAnswerIn: {
            /** Question Id */
            question_id: number;
            /** Selected Alternative Id */
            selected_alternative_id?: number | null;
        };
        /** DemoGradeIn */
        DemoGradeIn: {
            /** Answers */
            answers: components["schemas"]["DemoAnswerIn"][];
        };
        /** DemoGradeItemOut */
        DemoGradeItemOut: {
            /** Question Id */
            question_id: number;
            /** Is Correct */
            is_correct: boolean;
            /** Correct Alternative Id */
            correct_alternative_id: number;
            /** Explanation */
            explanation?: string | null;
        };
        /** DemoGradeOut */
        DemoGradeOut: {
            /** Items */
            items: components["schemas"]["DemoGradeItemOut"][];
            /** Correct */
            correct: number;
            /** Total */
            total: number;
        };
        /** DemoQuestionOut */
        DemoQuestionOut: {
            /** Id */
            id: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Alternatives */
            alternatives: components["schemas"]["DemoAlternativeOut"][];
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "facil" | "medio" | "dificil";
        /**
         * ExamAlternativeOut
         * @description Alternativa durante el examen: SIN is_correct ni
         *     distractor_justification. Esos datos solo se exponen después de
         *     submit (revisión de respuestas).
         */
        ExamAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** ExamAnswerIn */
        ExamAnswerIn: {
            /** Question Id */
            question_id: number;
            /** Selected Alternative Id */
            selected_alternative_id?: number | null;
            /**
             * Time Spent Ms
             * @default 0
             */
            time_spent_ms: number;
            /**
             * Flagged
             * @default false
             */
            flagged: boolean;
        };
        /** ExamAnswerState */
        ExamAnswerState: {
            /** Selected Alternative Id */
            selected_alternative_id?: number | null;
            /**
             * Time Spent Ms
             * @default 0
             */
            time_spent_ms: number;
            /**
             * Flagged
             * @default false
             */
            flagged: boolean;
        };
        /** ExamAttemptSummary */
        ExamAttemptSummary: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            status: components["schemas"]["AttemptStatus"];
            subject: components["schemas"]["Subject"];
            /** Total Questions */
            total_questions: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Estimated Score */
            estimated_score?: number | null;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            pace: components["schemas"]["Pace"];
            /** Axes */
            axes: string[];
        };
        /**
         * ExamConfigIn
         * @description Configuración elegida por el estudiante antes de comenzar.
         */
        ExamConfigIn: {
            /** @default m1 */
            subject: components["schemas"]["Subject"];
            /**
             * Question Count
             * @default 20
             */
            question_count: number;
            /** @default oficial */
            pace: components["schemas"]["Pace"];
            /** Axes */
            axes?: string[];
        };
        /** ExamConfigOut */
        ExamConfigOut: {
            subject: components["schemas"]["Subject"];
            /** Question Count */
            question_count: number;
            pace: components["schemas"]["Pace"];
            /** Axes */
            axes: string[];
        };
        /**
         * ExamOptionsOut
         * @description Todo lo que la pantalla de configuración necesita para armarse.
         */
        ExamOptionsOut: {
            subject: components["schemas"]["Subject"];
            /** Axes */
            axes: components["schemas"]["AxisOptionOut"][];
            /** Total Available */
            total_available: number;
            /** Seconds Per Question */
            seconds_per_question: number;
            /** Official Questions */
            official_questions: number;
            /** Official Duration Min */
            official_duration_min: number;
        };
        /** ExamQuestionOut */
        ExamQuestionOut: {
            /** Id */
            id: number;
            /** Skill Node Id */
            skill_node_id: number;
            /**
             * Skill Node Name
             * @default
             */
            skill_node_name: string;
            /**
             * Axis
             * @default
             */
            axis: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Image Url */
            image_url?: string | null;
            /** Alternatives */
            alternatives: components["schemas"]["ExamAlternativeOut"][];
        };
        /** ExamResultOut */
        ExamResultOut: {
            /** Attempt Id */
            attempt_id: number;
            status: components["schemas"]["AttemptStatus"];
            /** Total Questions */
            total_questions: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Omitted */
            omitted: number;
            /** Estimated Score */
            estimated_score: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            /** By Axis */
            by_axis: components["schemas"]["BreakdownItemOut"][];
            /** By Difficulty */
            by_difficulty: components["schemas"]["BreakdownItemOut"][];
            /** By Node */
            by_node: components["schemas"]["BreakdownItemOut"][];
        };
        /** ExamReviewOut */
        ExamReviewOut: {
            /** Attempt Id */
            attempt_id: number;
            status: components["schemas"]["AttemptStatus"];
            /** Questions */
            questions: components["schemas"]["ReviewQuestionOut"][];
            /** Node Diagnosis */
            node_diagnosis: components["schemas"]["NodeDiagnosisOut"][];
        };
        /** ExamStartOut */
        ExamStartOut: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            config: components["schemas"]["ExamConfigOut"];
            /** Questions */
            questions: components["schemas"]["ExamQuestionOut"][];
        };
        /** ExamStateOut */
        ExamStateOut: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            config: components["schemas"]["ExamConfigOut"];
            /** Questions */
            questions: components["schemas"]["ExamQuestionOut"][];
            status: components["schemas"]["AttemptStatus"];
            /** Answers */
            answers: {
                [key: string]: components["schemas"]["ExamAnswerState"];
            };
        };
        /** ForgotPasswordIn */
        ForgotPasswordIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * GoogleLoginIn
         * @description `credential` es el ID token (JWT) que entrega Google Identity Services.
         */
        GoogleLoginIn: {
            /** Credential */
            credential: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** NodeDiagnosisOut */
        NodeDiagnosisOut: {
            /** Skill Node Id */
            skill_node_id: number;
            /** Skill Node Code */
            skill_node_code: string;
            /** Skill Node Name */
            skill_node_name: string;
            /** Axis */
            axis: string;
            /** Total */
            total: number;
            /** Correct */
            correct: number;
            /** Accuracy */
            accuracy: number;
        };
        /**
         * Pace
         * @description Ritmo del ensayo: ajusta el tiempo respecto de la proporción oficial.
         *
         *     El oficial replica la razón de la PAES real; los otros dos existen porque a
         *     veces conviene entrenar bajo presión o dedicar más tiempo a razonar cuando
         *     recién se está estudiando la materia.
         * @enum {string}
         */
        Pace: "oficial" | "exigente" | "relajado";
        /** PracticeAlternativeOut */
        PracticeAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** PracticeAnswerIn */
        PracticeAnswerIn: {
            /** Question Id */
            question_id: number;
            /** Selected Alternative Id */
            selected_alternative_id: number;
        };
        /** PracticeAnswerOut */
        PracticeAnswerOut: {
            /** Is Correct */
            is_correct: boolean;
            /** Correct Alternative Id */
            correct_alternative_id: number;
            /** Explanation */
            explanation?: string | null;
            /** Node Accuracy */
            node_accuracy: number;
            /** Node Attempts */
            node_attempts: number;
            /**
             * Newly Unlocked
             * @default []
             */
            newly_unlocked: string[];
        };
        /** PracticeQuestionOut */
        PracticeQuestionOut: {
            /** Id */
            id: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Image Url */
            image_url?: string | null;
            /** Alternatives */
            alternatives: components["schemas"]["PracticeAlternativeOut"][];
        };
        /** PracticeStartOut */
        PracticeStartOut: {
            /** Node Code */
            node_code: string;
            /** Node Name */
            node_name: string;
            /** Questions */
            questions: components["schemas"]["PracticeQuestionOut"][];
        };
        /**
         * ProgressStatus
         * @enum {string}
         */
        ProgressStatus: "locked" | "unlocked" | "mastered";
        /** QuestionSafeOut */
        QuestionSafeOut: {
            /** Id */
            id: number;
            /** Skill Node Id */
            skill_node_id: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Image Url */
            image_url?: string | null;
            /** Alternatives */
            alternatives: components["schemas"]["AlternativeSafeOut"][];
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /**
         * RepasoOut
         * @description Sugerencia para el boton "Ensayo de repaso": los ejes de los nodos
         *     donde el estudiante rinde peor, reusando el mismo progreso del Arbol de
         *     Habilidades. has_data en False significa que todavia no hay suficientes
         *     respuestas para sugerir nada (usuario nuevo).
         */
        RepasoOut: {
            /** Has Data */
            has_data: boolean;
            /** Axes */
            axes: string[];
            /** Axis Labels */
            axis_labels: string[];
        };
        /** ResetPasswordIn */
        ResetPasswordIn: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ReviewAlternativeOut
         * @description Alternativa en la revisión post-examen: SÍ incluye is_correct y
         *     distractor_justification — el porqué de cada error.
         */
        ReviewAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Is Correct */
            is_correct: boolean;
            /** Distractor Justification */
            distractor_justification?: string | null;
            /** Selected */
            selected: boolean;
        };
        /** ReviewQuestionOut */
        ReviewQuestionOut: {
            /** Id */
            id: number;
            /** Stem */
            stem: string;
            /** Explanation */
            explanation?: string | null;
            difficulty: components["schemas"]["Difficulty"];
            /** Skill Node Id */
            skill_node_id: number;
            /** Skill Node Code */
            skill_node_code: string;
            /** Skill Node Name */
            skill_node_name: string;
            /** Axis */
            axis: string;
            /** Time Spent Ms */
            time_spent_ms: number;
            /** Answered Correctly */
            answered_correctly: boolean | null;
            /** Alternatives */
            alternatives: components["schemas"]["ReviewAlternativeOut"][];
        };
        /**
         * SkillAxis
         * @enum {string}
         */
        SkillAxis: "numeros" | "algebra" | "geometria" | "probabilidad";
        /** SkillNodeProgressOut */
        SkillNodeProgressOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            axis: components["schemas"]["SkillAxis"];
            subject: components["schemas"]["Subject"];
            /** Tier */
            tier: number;
            /** Unlock Threshold */
            unlock_threshold: number;
            /** Display Order */
            display_order: number;
            /**
             * Prerequisite Codes
             * @default []
             */
            prerequisite_codes: string[];
            status: components["schemas"]["ProgressStatus"];
            /** Accuracy */
            accuracy: number;
            /** Attempts */
            attempts: number;
        };
        /**
         * Subject
         * @description Prueba PAES a la que pertenece un nodo. M2 evalúa "todos los
         *     conocimientos de M1, además de" contenido propio (ver temario DEMRE), por
         *     eso M2 no duplica los nodos de M1: los reutiliza y solo agrega los nodos
         *     exclusivos de M2. `exam_focus.service.SUBJECT_INCLUDES` es la fuente de
         *     verdad de qué subjects entran al banco de preguntas de cada prueba.
         * @enum {string}
         */
        Subject: "m1" | "m2";
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UpdateMeIn */
        UpdateMeIn: {
            /** Name */
            name?: string | null;
            /** Current Password */
            current_password?: string | null;
            /** New Password */
            new_password?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Has Password
             * @default true
             */
            has_password: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_config_api_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigOut"];
                };
            };
        };
    };
    login_with_google_api_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_api_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skill_nodes_api_skill_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNodeProgressOut"][];
                };
            };
        };
    };
    get_recommended_node_api_skill_tree_recommended_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNodeProgressOut"] | null;
                };
            };
        };
    };
    get_skill_node_api_skill_tree__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNodeProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_questions_get: {
        parameters: {
            query?: {
                skill_node_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSafeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_options_api_exam_options_get: {
        parameters: {
            query?: {
                subject?: components["schemas"]["Subject"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamOptionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repaso_api_exam_repaso_get: {
        parameters: {
            query?: {
                subject?: components["schemas"]["Subject"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepasoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exam_attempts_api_exam_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttemptSummary"][];
                };
            };
        };
    };
    start_exam_api_exam_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExamConfigIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_state_api_exam__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exam_attempt_api_exam__attempt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_api_exam__attempt_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_exam_api_exam__attempt_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_result_api_exam__attempt_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_review_api_exam__attempt_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_questions_api_practice__code__questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_practice_question_api_practice__code__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummaryOut"];
                };
            };
        };
    };
    get_demo_questions_api_demo_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoQuestionOut"][];
                };
            };
        };
    };
    grade_demo_api_demo_grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoGradeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoGradeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
