/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Config
         * @description Qué puede hacer este servidor, para que la interfaz no prometa de más.
         *
         *     Sin SMTP configurado, "te llegará un correo con las instrucciones" es una
         *     promesa incumplible: el enlace de recuperación se genera igual pero queda
         *     en el log, y el estudiante espera algo que nunca llega. La pantalla
         *     necesita saberlo para decir la verdad.
         */
        get: operations["auth_config_api_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login With Google */
        post: operations["login_with_google_api_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Siempre responde 204, exista o no el correo: no revela qué cuentas
         *     están registradas.
         */
        post: operations["forgot_password_api_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_auth_me_patch"];
        trace?: never;
    };
    "/api/skill-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skill Nodes */
        get: operations["list_skill_nodes_api_skill_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skill-tree/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommended Node */
        get: operations["get_recommended_node_api_skill_tree_recommended_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skill-tree/{code}/leccion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lesson
         * @description La teoría del nodo. 404 si el nodo todavía no tiene lección escrita.
         */
        get: operations["get_lesson_api_skill_tree__code__leccion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skill-tree/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill Node */
        get: operations["get_skill_node_api_skill_tree__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Questions
         * @description Nunca expone is_correct ni distractor_justification (ver
         *     QuestionSafeOut) — misma regla de integridad que el Modo Examen.
         */
        get: operations["list_questions_api_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Content Stats
         * @description Totales del banco. Público y sin autenticación: la portada lo usa.
         *
         *     No revela ninguna pregunta, solo cuántas hay.
         */
        get: operations["content_stats_api_questions_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Options
         * @description Ejes y disponibilidad del banco, para la pantalla de configuración.
         */
        get: operations["get_exam_options_api_exam_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/repaso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repaso
         * @description Sugerencia para el botón "Ensayo de repaso" en la config del ensayo.
         */
        get: operations["get_repaso_api_exam_repaso_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exam Attempts */
        get: operations["list_exam_attempts_api_exam_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Exam */
        post: operations["start_exam_api_exam_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam State */
        get: operations["get_exam_state_api_exam__attempt_id__get"];
        put?: never;
        post?: never;
        /** Delete Exam Attempt */
        delete: operations["delete_exam_attempt_api_exam__attempt_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Question */
        post: operations["answer_question_api_exam__attempt_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Exam */
        post: operations["submit_exam_api_exam__attempt_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Result
         * @description Mismo resumen que devuelve submit, para volver a abrir un ensayo pasado.
         */
        get: operations["get_exam_result_api_exam__attempt_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/{attempt_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam Review */
        get: operations["get_exam_review_api_exam__attempt_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/carreras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar Carreras */
        get: operations["buscar_carreras_api_meta_carreras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Meta */
        get: operations["ver_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/postulaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agregar Postulacion
         * @description Agrega una carrera al final de la lista de preferencias.
         */
        post: operations["agregar_postulacion_api_meta_postulaciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/orden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reordenar
         * @description Reordena la lista. El orden decide dónde queda uno, así que es parte
         *     de la decisión y no un detalle de presentación.
         */
        put: operations["reordenar_api_meta_orden_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/postulaciones/{carrera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Quitar Postulacion */
        delete: operations["quitar_postulacion_api_meta_postulaciones__carrera_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/notas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Guardar Notas */
        put: operations["guardar_notas_api_meta_notas_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/{code}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice Questions */
        get: operations["get_practice_questions_api_practice__code__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/{code}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Practice Question */
        post: operations["answer_practice_question_api_practice__code__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Demo Questions
         * @description Preguntas de prueba SIN cuenta: pública, sin auth, sin persistir nada.
         *     Solo fácil/medio -- la demo busca enganchar, no frustrar en el primer
         *     contacto con la plataforma.
         */
        get: operations["get_demo_questions_api_demo_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grade Demo
         * @description Corrige la demo al vuelo, sin guardar ningún intento -- no hay usuario
         *     todavía, así que no hay dónde guardarlo.
         */
        post: operations["grade_demo_api_demo_grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/pageview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar Visita
         * @description Registra una visita. Público: la mayor parte del tráfico que interesa
         *     medir es de gente que todavía no tiene cuenta.
         *
         *     Nunca falla hacia el usuario: medir no puede romper la navegación.
         */
        post: operations["registrar_visita_api_metrics_pageview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Todo el panel en una sola llamada: son consultas agregadas y baratas, y
         *     partirlas en cinco endpoints solo multiplicaría los viajes.
         */
        get: operations["metrics_api_admin_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminMetricsOut */
        AdminMetricsOut: {
            /**
             * Generado En
             * Format: date-time
             */
            generado_en: string;
            usuarios: components["schemas"]["UsuariosOut"];
            sesiones: components["schemas"]["SesionesOut"];
            visitas: components["schemas"]["VisitasOut"];
            contenido: components["schemas"]["ContenidoOut"];
        };
        /**
         * AlternativeSafeOut
         * @description Alternativa sin is_correct ni distractor_justification — para
         *     listados públicos/autenticados que no deben revelar la respuesta.
         */
        AlternativeSafeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** AnalyticsSummaryOut */
        AnalyticsSummaryOut: {
            /** Current Streak Days */
            current_streak_days: number;
            /**
             * Active Days
             * @default 0
             */
            active_days: number;
            /** Total Questions Answered */
            total_questions_answered: number;
            /** Total Correct */
            total_correct: number;
            /** Overall Accuracy */
            overall_accuracy: number | null;
            /** Total Minutes Practiced */
            total_minutes_practiced: number;
            /** Daily */
            daily: components["schemas"]["DailyStat"][];
        };
        /** AporteOut */
        AporteOut: {
            /** Factor */
            factor: string;
            /** Etiqueta */
            etiqueta: string;
            /** Ponderacion */
            ponderacion: number;
            /** Puntaje */
            puntaje: number | null;
            /** Aporte */
            aporte: number;
            /** Por Cada 10 */
            por_cada_10: number;
            /** Origen */
            origen: string;
        };
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "in_progress" | "submitted" | "abandoned";
        /**
         * AuthConfigOut
         * @description Qué puede hacer este despliegue, para que la interfaz no prometa de más.
         */
        AuthConfigOut: {
            /** Google Enabled */
            google_enabled: boolean;
            /**
             * Email Enabled
             * @default false
             */
            email_enabled: boolean;
        };
        /**
         * AxisOptionOut
         * @description Un eje temático y cuántas preguntas hay disponibles en el banco.
         */
        AxisOptionOut: {
            /** Axis */
            axis: string;
            /** Label */
            label: string;
            /** Available */
            available: number;
        };
        /**
         * BreakdownItemOut
         * @description Desempeño agrupado por eje, nodo o dificultad.
         */
        BreakdownItemOut: {
            /** Name */
            name: string;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Omitted */
            omitted: number;
            /** Total */
            total: number;
            /** Percentage */
            percentage: number;
        };
        /** CarreraOut */
        CarreraOut: {
            /** Id */
            id: number;
            /** Codigo */
            codigo: string;
            /** Universidad */
            universidad: string;
            /** Nombre */
            nombre: string;
            /** Sede */
            sede: string;
            /** Nem */
            nem?: number | null;
            /** Ranking */
            ranking?: number | null;
            /** Lectora */
            lectora?: number | null;
            /** M1 */
            m1?: number | null;
            /** Historia */
            historia?: number | null;
            /** Ciencias */
            ciencias?: number | null;
            /** M2 */
            m2?: number | null;
            /** Prueba Especial */
            prueba_especial?: number | null;
            /** Electivo Alternativo */
            electivo_alternativo: boolean;
            /** Ponderado Min */
            ponderado_min?: number | null;
            /** Promedio Min */
            promedio_min?: number | null;
            /** Vacantes */
            vacantes?: number | null;
            /** Proceso */
            proceso: number;
            /** Fuente */
            fuente: string;
        };
        /** ContenidoOut */
        ContenidoOut: {
            ensayos: components["schemas"]["ConteoPeriodo"];
            /** Puntaje Promedio */
            puntaje_promedio: number | null;
            /** Respuestas Totales */
            respuestas_totales: number;
            /** Tasa Acierto Global */
            tasa_acierto_global: number | null;
            /** Preguntas Mas Falladas */
            preguntas_mas_falladas: components["schemas"]["PreguntaFallada"][];
            /** Nodos Mas Flojos */
            nodos_mas_flojos: components["schemas"]["NodoFlojo"][];
        };
        /**
         * ContentStatsOut
         * @description Cifras públicas del banco, para que la portada no invente números.
         *
         *     La landing muestra "N preguntas verificadas"; ese N sale de contar la
         *     tabla, no de una constante escrita a mano que envejece en silencio.
         */
        ContentStatsOut: {
            /** Questions */
            questions: number;
            /** Passages */
            passages: number;
            /** Skill Nodes */
            skill_nodes: number;
            /** Subjects */
            subjects: number;
        };
        /**
         * ConteoPeriodo
         * @description El mismo número medido en tres ventanas. Un solo total no dice si algo
         *     está creciendo o si pasó hace meses.
         */
        ConteoPeriodo: {
            /** Hoy */
            hoy: number;
            /** Ultimos 7 */
            ultimos_7: number;
            /** Ultimos 30 */
            ultimos_30: number;
            /** Total */
            total: number;
        };
        /** DailyStat */
        DailyStat: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Questions Answered */
            questions_answered: number;
            /** Correct */
            correct: number;
            /** Accuracy */
            accuracy: number | null;
            /** Minutes Practiced */
            minutes_practiced: number;
        };
        /**
         * DemoAlternativeOut
         * @description Sin is_correct: misma regla de integridad que el Modo Examen.
         */
        DemoAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** DemoAnswerIn */
        DemoAnswerIn: {
            /** Question Id */
            question_id: number;
            /** Selected Alternative Id */
            selected_alternative_id?: number | null;
        };
        /** DemoGradeIn */
        DemoGradeIn: {
            /** Answers */
            answers: components["schemas"]["DemoAnswerIn"][];
        };
        /** DemoGradeItemOut */
        DemoGradeItemOut: {
            /** Question Id */
            question_id: number;
            /** Is Correct */
            is_correct: boolean;
            /** Correct Alternative Id */
            correct_alternative_id: number;
            /** Explanation */
            explanation?: string | null;
        };
        /** DemoGradeOut */
        DemoGradeOut: {
            /** Items */
            items: components["schemas"]["DemoGradeItemOut"][];
            /** Correct */
            correct: number;
            /** Total */
            total: number;
        };
        /** DemoQuestionOut */
        DemoQuestionOut: {
            /** Id */
            id: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Alternatives */
            alternatives: components["schemas"]["DemoAlternativeOut"][];
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "facil" | "medio" | "dificil";
        /**
         * ExamAlternativeOut
         * @description Alternativa durante el examen: SIN is_correct ni
         *     distractor_justification. Esos datos solo se exponen después de
         *     submit (revisión de respuestas).
         */
        ExamAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** ExamAnswerIn */
        ExamAnswerIn: {
            /** Question Id */
            question_id: number;
            /** Selected Alternative Id */
            selected_alternative_id?: number | null;
            /**
             * Time Spent Ms
             * @default 0
             */
            time_spent_ms: number;
            /**
             * Flagged
             * @default false
             */
            flagged: boolean;
        };
        /** ExamAnswerState */
        ExamAnswerState: {
            /** Selected Alternative Id */
            selected_alternative_id?: number | null;
            /**
             * Time Spent Ms
             * @default 0
             */
            time_spent_ms: number;
            /**
             * Flagged
             * @default false
             */
            flagged: boolean;
        };
        /** ExamAttemptSummary */
        ExamAttemptSummary: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            status: components["schemas"]["AttemptStatus"];
            subject: components["schemas"]["Subject"];
            /** Total Questions */
            total_questions: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Estimated Score */
            estimated_score?: number | null;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            pace: components["schemas"]["Pace"];
            /** Axes */
            axes: string[];
        };
        /**
         * ExamConfigIn
         * @description Configuración elegida por el estudiante antes de comenzar.
         */
        ExamConfigIn: {
            /** @default m1 */
            subject: components["schemas"]["Subject"];
            /**
             * Question Count
             * @default 20
             */
            question_count: number;
            /** @default oficial */
            pace: components["schemas"]["Pace"];
            /** Axes */
            axes?: string[];
        };
        /** ExamConfigOut */
        ExamConfigOut: {
            subject: components["schemas"]["Subject"];
            /** Question Count */
            question_count: number;
            pace: components["schemas"]["Pace"];
            /** Axes */
            axes: string[];
        };
        /**
         * ExamOptionsOut
         * @description Todo lo que la pantalla de configuración necesita para armarse.
         */
        ExamOptionsOut: {
            subject: components["schemas"]["Subject"];
            /** Axes */
            axes: components["schemas"]["AxisOptionOut"][];
            /** Total Available */
            total_available: number;
            /** Seconds Per Question */
            seconds_per_question: number;
            /** Official Questions */
            official_questions: number;
            /** Official Duration Min */
            official_duration_min: number;
        };
        /** ExamQuestionOut */
        ExamQuestionOut: {
            /** Id */
            id: number;
            /** Skill Node Id */
            skill_node_id: number;
            /**
             * Skill Node Name
             * @default
             */
            skill_node_name: string;
            /**
             * Axis
             * @default
             */
            axis: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Image Url */
            image_url?: string | null;
            passage?: components["schemas"]["PassageOut"] | null;
            /** Alternatives */
            alternatives: components["schemas"]["ExamAlternativeOut"][];
        };
        /** ExamResultOut */
        ExamResultOut: {
            /** Attempt Id */
            attempt_id: number;
            status: components["schemas"]["AttemptStatus"];
            /** Total Questions */
            total_questions: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Omitted */
            omitted: number;
            /** Estimated Score */
            estimated_score: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            /** By Axis */
            by_axis: components["schemas"]["BreakdownItemOut"][];
            /** By Difficulty */
            by_difficulty: components["schemas"]["BreakdownItemOut"][];
            /** By Node */
            by_node: components["schemas"]["BreakdownItemOut"][];
        };
        /** ExamReviewOut */
        ExamReviewOut: {
            /** Attempt Id */
            attempt_id: number;
            status: components["schemas"]["AttemptStatus"];
            /** Questions */
            questions: components["schemas"]["ReviewQuestionOut"][];
            /** Node Diagnosis */
            node_diagnosis: components["schemas"]["NodeDiagnosisOut"][];
        };
        /** ExamStartOut */
        ExamStartOut: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            config: components["schemas"]["ExamConfigOut"];
            /** Questions */
            questions: components["schemas"]["ExamQuestionOut"][];
        };
        /** ExamStateOut */
        ExamStateOut: {
            /** Attempt Id */
            attempt_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Limit Seconds */
            duration_limit_seconds: number;
            config: components["schemas"]["ExamConfigOut"];
            /** Questions */
            questions: components["schemas"]["ExamQuestionOut"][];
            status: components["schemas"]["AttemptStatus"];
            /** Answers */
            answers: {
                [key: string]: components["schemas"]["ExamAnswerState"];
            };
        };
        /** ForgotPasswordIn */
        ForgotPasswordIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * GoogleLoginIn
         * @description `credential` es el ID token (JWT) que entrega Google Identity Services.
         */
        GoogleLoginIn: {
            /** Credential */
            credential: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LessonOut
         * @description La teoría del nodo: lo que se estudia antes de practicar.
         */
        LessonOut: {
            /** Node Code */
            node_code: string;
            /** Node Name */
            node_name: string;
            /** Intro */
            intro: string;
            /** Theory */
            theory: string;
            /** Example Statement */
            example_statement: string;
            /** Example Steps */
            example_steps: components["schemas"]["LessonStepOut"][];
            /** Common Error */
            common_error?: string | null;
        };
        /** LessonStepOut */
        LessonStepOut: {
            /** Accion */
            accion: string;
            /** Porque */
            porque: string;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MetaOut */
        MetaOut: {
            /** Postulaciones */
            postulaciones: components["schemas"]["PostulacionOut"][];
            /** Puntaje Nem */
            puntaje_nem: number | null;
            /** Puntaje Ranking */
            puntaje_ranking: number | null;
            proyeccion: components["schemas"]["ProyeccionOut"];
            /** Plan */
            plan: components["schemas"]["NodoDebilOut"][];
            /** Plan Para */
            plan_para: string | null;
        };
        /** NodeDiagnosisOut */
        NodeDiagnosisOut: {
            /** Skill Node Id */
            skill_node_id: number;
            /** Skill Node Code */
            skill_node_code: string;
            /** Skill Node Name */
            skill_node_name: string;
            /** Axis */
            axis: string;
            /** Total */
            total: number;
            /** Correct */
            correct: number;
            /** Accuracy */
            accuracy: number;
        };
        /** NodoDebilOut */
        NodoDebilOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Axis */
            axis: string;
            /** Accuracy */
            accuracy: number;
            /** Attempts */
            attempts: number;
            /** Has Lesson */
            has_lesson: boolean;
        };
        /** NodoFlojo */
        NodoFlojo: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Respuestas */
            respuestas: number;
            /** Tasa Acierto */
            tasa_acierto: number;
        };
        /** NotasIn */
        NotasIn: {
            /** Puntaje Nem */
            puntaje_nem?: number | null;
            /** Puntaje Ranking */
            puntaje_ranking?: number | null;
        };
        /**
         * OrdenIn
         * @description Los ids de carrera en el orden de preferencia deseado.
         */
        OrdenIn: {
            /** Carrera Ids */
            carrera_ids: number[];
        };
        /**
         * Pace
         * @description Ritmo del ensayo: ajusta el tiempo respecto de la proporción oficial.
         *
         *     El oficial replica la razón de la PAES real; los otros dos existen porque a
         *     veces conviene entrenar bajo presión o dedicar más tiempo a razonar cuando
         *     recién se está estudiando la materia.
         * @enum {string}
         */
        Pace: "oficial" | "exigente" | "relajado";
        /**
         * PageViewIn
         * @description Lo que manda el navegador en cada cambio de página.
         */
        PageViewIn: {
            /** Path */
            path: string;
            /** Visitor Id */
            visitor_id: string;
        };
        /**
         * PassageOut
         * @description Texto base de una pregunta de Competencia Lectora.
         */
        PassageOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Kind */
            kind: string;
            /** Source Note */
            source_note?: string | null;
        };
        /** PostulacionOut */
        PostulacionOut: {
            /** Preferencia */
            preferencia: number;
            carrera: components["schemas"]["CarreraOut"];
            /** Ponderado */
            ponderado: number | null;
            /** Brecha */
            brecha: number | null;
            /** Alcanza */
            alcanza: boolean | null;
            /** Aportes */
            aportes: components["schemas"]["AporteOut"][];
            /** Faltantes */
            faltantes: string[];
            /** Mejor Palanca */
            mejor_palanca: string | null;
        };
        /** PostularIn */
        PostularIn: {
            /** Carrera Id */
            carrera_id: number;
        };
        /** PracticeAlternativeOut */
        PracticeAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** PracticeAnswerIn */
        PracticeAnswerIn: {
            /** Question Id */
            question_id: number;
            /** Selected Alternative Id */
            selected_alternative_id: number;
        };
        /** PracticeAnswerOut */
        PracticeAnswerOut: {
            /** Is Correct */
            is_correct: boolean;
            /** Correct Alternative Id */
            correct_alternative_id: number;
            /** Explanation */
            explanation?: string | null;
            /** Node Accuracy */
            node_accuracy: number;
            /** Node Attempts */
            node_attempts: number;
            /**
             * Newly Unlocked
             * @default []
             */
            newly_unlocked: string[];
        };
        /** PracticeQuestionOut */
        PracticeQuestionOut: {
            /** Id */
            id: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Image Url */
            image_url?: string | null;
            /** Alternatives */
            alternatives: components["schemas"]["PracticeAlternativeOut"][];
        };
        /** PracticeStartOut */
        PracticeStartOut: {
            /** Node Code */
            node_code: string;
            /** Node Name */
            node_name: string;
            /** Questions */
            questions: components["schemas"]["PracticeQuestionOut"][];
        };
        /** PreguntaFallada */
        PreguntaFallada: {
            /** Question Id */
            question_id: number;
            /** Stem */
            stem: string;
            /** Axis */
            axis: string;
            /** Respuestas */
            respuestas: number;
            /** Tasa Acierto */
            tasa_acierto: number;
        };
        /**
         * ProgressStatus
         * @enum {string}
         */
        ProgressStatus: "locked" | "unlocked" | "mastered";
        /**
         * ProyeccionOut
         * @description Ritmo de mejora medido sobre los ensayos ya rendidos.
         */
        ProyeccionOut: {
            /** Puntos Por Mes */
            puntos_por_mes: number | null;
            /** Ensayos Considerados */
            ensayos_considerados: number;
            /** Dias Para Paes */
            dias_para_paes: number | null;
            /** Proyectado */
            proyectado: number | null;
        };
        /** QuestionSafeOut */
        QuestionSafeOut: {
            /** Id */
            id: number;
            /** Skill Node Id */
            skill_node_id: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Stem */
            stem: string;
            /** Image Url */
            image_url?: string | null;
            /** Alternatives */
            alternatives: components["schemas"]["AlternativeSafeOut"][];
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /**
         * RepasoOut
         * @description Sugerencia para el boton "Ensayo de repaso": los ejes de los nodos
         *     donde el estudiante rinde peor, reusando el mismo progreso del Arbol de
         *     Habilidades. has_data en False significa que todavia no hay suficientes
         *     respuestas para sugerir nada (usuario nuevo).
         */
        RepasoOut: {
            /** Has Data */
            has_data: boolean;
            /** Axes */
            axes: string[];
            /** Axis Labels */
            axis_labels: string[];
        };
        /** ResetPasswordIn */
        ResetPasswordIn: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ReviewAlternativeOut
         * @description Alternativa en la revisión post-examen: SÍ incluye is_correct y
         *     distractor_justification — el porqué de cada error.
         */
        ReviewAlternativeOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Is Correct */
            is_correct: boolean;
            /** Distractor Justification */
            distractor_justification?: string | null;
            /** Selected */
            selected: boolean;
        };
        /** ReviewQuestionOut */
        ReviewQuestionOut: {
            /** Id */
            id: number;
            /** Stem */
            stem: string;
            /** Explanation */
            explanation?: string | null;
            difficulty: components["schemas"]["Difficulty"];
            /** Skill Node Id */
            skill_node_id: number;
            /** Skill Node Code */
            skill_node_code: string;
            /** Skill Node Name */
            skill_node_name: string;
            /** Axis */
            axis: string;
            /** Time Spent Ms */
            time_spent_ms: number;
            /** Answered Correctly */
            answered_correctly: boolean | null;
            /** Alternatives */
            alternatives: components["schemas"]["ReviewAlternativeOut"][];
        };
        /** RutaVisitas */
        RutaVisitas: {
            /** Path */
            path: string;
            /** Visitas */
            visitas: number;
            /** Visitantes */
            visitantes: number;
        };
        /** SerieDia */
        SerieDia: {
            /** Dia */
            dia: string;
            /** Valor */
            valor: number;
        };
        /** SesionesOut */
        SesionesOut: {
            entradas: components["schemas"]["ConteoPeriodo"];
            /** Activos 7 */
            activos_7: number;
            /** Activos 30 */
            activos_30: number;
            /** Por Metodo */
            por_metodo: {
                [key: string]: number;
            };
            /** Entradas Por Dia */
            entradas_por_dia: components["schemas"]["SerieDia"][];
        };
        /**
         * SkillAxis
         * @description Dimensión del temario a la que pertenece un nodo.
         *
         *     En matemática son los cuatro ejes temáticos del DEMRE. En Competencia
         *     Lectora no hay ejes de contenido: la prueba se organiza por las tres
         *     habilidades que declara el temario (localizar, interpretar y evaluar), y
         *     son esas las que ocupan el lugar del eje.
         * @enum {string}
         */
        SkillAxis: "numeros" | "algebra" | "geometria" | "probabilidad" | "localizar" | "interpretar" | "evaluar" | "biologia" | "fisica" | "quimica" | "historia" | "ciudadania" | "economia";
        /** SkillNodeProgressOut */
        SkillNodeProgressOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            axis: components["schemas"]["SkillAxis"];
            subject: components["schemas"]["Subject"];
            /** Tier */
            tier: number;
            /** Unlock Threshold */
            unlock_threshold: number;
            /** Display Order */
            display_order: number;
            /**
             * Prerequisite Codes
             * @default []
             */
            prerequisite_codes: string[];
            status: components["schemas"]["ProgressStatus"];
            /** Accuracy */
            accuracy: number;
            /** Attempts */
            attempts: number;
            /**
             * Has Lesson
             * @default false
             */
            has_lesson: boolean;
        };
        /**
         * Subject
         * @description Prueba PAES a la que pertenece un nodo. M2 evalúa "todos los
         *     conocimientos de M1, además de" contenido propio (ver temario DEMRE), por
         *     eso M2 no duplica los nodos de M1: los reutiliza y solo agrega los nodos
         *     exclusivos de M2. `exam_focus.service.SUBJECT_INCLUDES` es la fuente de
         *     verdad de qué subjects entran al banco de preguntas de cada prueba.
         * @enum {string}
         */
        Subject: "m1" | "m2" | "lectora" | "ciencias" | "historia";
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UpdateMeIn */
        UpdateMeIn: {
            /** Name */
            name?: string | null;
            /** Current Password */
            current_password?: string | null;
            /** New Password */
            new_password?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Has Password
             * @default true
             */
            has_password: boolean;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** UsuarioResumen */
        UsuarioResumen: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
            /** Ensayos */
            ensayos: number;
        };
        /** UsuariosOut */
        UsuariosOut: {
            registros: components["schemas"]["ConteoPeriodo"];
            /** Nuevos Por Dia */
            nuevos_por_dia: components["schemas"]["SerieDia"][];
            /** Ultimos */
            ultimos: components["schemas"]["UsuarioResumen"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitasOut */
        VisitasOut: {
            vistas: components["schemas"]["ConteoPeriodo"];
            visitantes: components["schemas"]["ConteoPeriodo"];
            /** Anonimas 7 */
            anonimas_7: number;
            /** Vistas Por Dia */
            vistas_por_dia: components["schemas"]["SerieDia"][];
            /** Top Rutas */
            top_rutas: components["schemas"]["RutaVisitas"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_config_api_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigOut"];
                };
            };
        };
    };
    login_with_google_api_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_api_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skill_nodes_api_skill_tree_get: {
        parameters: {
            query?: {
                /** @description Prueba cuyo temario se quiere ver. El árbol es distinto por prueba: cada una tiene sus propios ejes y prerrequisitos. */
                subject?: components["schemas"]["Subject"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNodeProgressOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommended_node_api_skill_tree_recommended_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNodeProgressOut"] | null;
                };
            };
        };
    };
    get_lesson_api_skill_tree__code__leccion_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_node_api_skill_tree__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNodeProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_questions_get: {
        parameters: {
            query?: {
                skill_node_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSafeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_stats_api_questions_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentStatsOut"];
                };
            };
        };
    };
    get_exam_options_api_exam_options_get: {
        parameters: {
            query?: {
                subject?: components["schemas"]["Subject"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamOptionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repaso_api_exam_repaso_get: {
        parameters: {
            query?: {
                subject?: components["schemas"]["Subject"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepasoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exam_attempts_api_exam_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttemptSummary"][];
                };
            };
        };
    };
    start_exam_api_exam_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExamConfigIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_state_api_exam__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exam_attempt_api_exam__attempt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_api_exam__attempt_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_exam_api_exam__attempt_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_result_api_exam__attempt_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_review_api_exam__attempt_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_carreras_api_meta_carreras_get: {
        parameters: {
            query: {
                /** @description Nombre de carrera, universidad o sede */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarreraOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    agregar_postulacion_api_meta_postulaciones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostularIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reordenar_api_meta_orden_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quitar_postulacion_api_meta_postulaciones__carrera_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrera_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guardar_notas_api_meta_notas_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotasIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_questions_api_practice__code__questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_practice_question_api_practice__code__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummaryOut"];
                };
            };
        };
    };
    get_demo_questions_api_demo_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoQuestionOut"][];
                };
            };
        };
    };
    grade_demo_api_demo_grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoGradeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoGradeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_visita_api_metrics_pageview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageViewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_admin_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMetricsOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
