"""columna de busqueda de carreras

Revision ID: 12d98019c3ca
Revises: 411a4e38f7ab
Create Date: 2026-08-15 04:39:10.470066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d98019c3ca'
down_revision: Union[str, Sequence[str], None] = '411a4e38f7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Agrega la columna de búsqueda sin tildes.

    En tres pasos porque la tabla ya tiene filas: una columna NOT NULL no se
    puede agregar de golpe sobre datos existentes. Se crea nullable, se rellena
    con los nombres normalizados, y recién ahí se exige.

    El relleno usa `translate` para quitar las tildes en SQL; el seed la vuelve
    a escribir después con la misma normalización de Python, así que basta con
    que acá quede un valor razonable y no nulo.
    """
    op.add_column("carreras", sa.Column("busqueda", sa.String(length=400), nullable=True))

    op.execute(
        """
        UPDATE carreras
        SET busqueda = lower(
            translate(
                nombre || ' ' || universidad || ' ' || sede,
                'áéíóúüñÁÉÍÓÚÜÑ',
                'aeiouunAEIOUUN'
            )
        )
        """
    )

    op.alter_column("carreras", "busqueda", nullable=False)
    op.create_index(op.f("ix_carreras_busqueda"), "carreras", ["busqueda"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carreras_busqueda'), table_name='carreras')
    op.drop_column('carreras', 'busqueda')
    # ### end Alembic commands ###
