"""carreras y meta del estudiante

Revision ID: 411a4e38f7ab
Revises: 71ff4d25412a
Create Date: 2026-08-15 04:21:32.661950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411a4e38f7ab'
down_revision: Union[str, Sequence[str], None] = '71ff4d25412a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('universidad', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('sede', sa.String(length=120), nullable=False),
    sa.Column('nem', sa.Float(), nullable=True),
    sa.Column('ranking', sa.Float(), nullable=True),
    sa.Column('lectora', sa.Float(), nullable=True),
    sa.Column('m1', sa.Float(), nullable=True),
    sa.Column('historia', sa.Float(), nullable=True),
    sa.Column('ciencias', sa.Float(), nullable=True),
    sa.Column('m2', sa.Float(), nullable=True),
    sa.Column('prueba_especial', sa.Float(), nullable=True),
    sa.Column('electivo_alternativo', sa.Boolean(), nullable=False),
    sa.Column('proceso', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carreras_codigo'), 'carreras', ['codigo'], unique=False)
    op.create_index(op.f('ix_carreras_nombre'), 'carreras', ['nombre'], unique=False)
    op.create_index(op.f('ix_carreras_universidad'), 'carreras', ['universidad'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('puntaje_nem', sa.Integer(), nullable=True),
    sa.Column('puntaje_ranking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_carrera_id'), 'user_goals', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_carrera_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_carreras_universidad'), table_name='carreras')
    op.drop_index(op.f('ix_carreras_nombre'), table_name='carreras')
    op.drop_index(op.f('ix_carreras_codigo'), table_name='carreras')
    op.drop_table('carreras')
    # ### end Alembic commands ###
