"""tabla practice_answers para incluir el modo practica en analitica

Revision ID: 4b4def55d69c
Revises: 70f14cd65bed
Create Date: 2026-08-13 03:01:55.405205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4def55d69c'
down_revision: Union[str, Sequence[str], None] = '70f14cd65bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_answers_question_id'), 'practice_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_practice_answers_skill_node_id'), 'practice_answers', ['skill_node_id'], unique=False)
    op.create_index(op.f('ix_practice_answers_user_id'), 'practice_answers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_answers_user_id'), table_name='practice_answers')
    op.drop_index(op.f('ix_practice_answers_skill_node_id'), table_name='practice_answers')
    op.drop_index(op.f('ix_practice_answers_question_id'), table_name='practice_answers')
    op.drop_table('practice_answers')
    # ### end Alembic commands ###
