"""lecciones del arbol de habilidades

Revision ID: 71ff4d25412a
Revises: ee1cd1ac1478
Create Date: 2026-08-15 03:02:56.073421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ff4d25412a'
down_revision: Union[str, Sequence[str], None] = 'ee1cd1ac1478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('theory', sa.Text(), nullable=False),
    sa.Column('example_statement', sa.Text(), nullable=False),
    sa.Column('example_steps', sa.JSON(), nullable=False),
    sa.Column('common_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_skill_node_id'), 'lessons', ['skill_node_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_skill_node_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
