"""suscripciones y codigos promocionales

Revision ID: 80ac40c7905a
Revises: 9ba90decdcbf
Create Date: 2026-08-15 16:05:03.289891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ac40c7905a'
down_revision: Union[str, Sequence[str], None] = '9ba90decdcbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('plan', sa.Enum('GRATIS', 'PRO', 'COLEGIOS', name='plan'), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('usos_maximos', sa.Integer(), nullable=False),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.Column('vence_el', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_codigo'), 'promo_codes', ['codigo'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('GRATIS', 'PRO', 'COLEGIOS', name='plan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELED', name='subscriptionstatus'), nullable=False),
    sa.Column('origen', sa.Enum('PAGO', 'CODIGO', 'MANUAL', name='origen'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('codigo', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_promo_codes_codigo'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
