"""explicacion paso a paso por pregunta

Revision ID: 8c46c0ee1300
Revises: 31589cf011de
Create Date: 2026-08-12 16:47:58.119632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c46c0ee1300'
down_revision: Union[str, Sequence[str], None] = '31589cf011de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'explanation')
    # ### end Alembic commands ###
