"""lista de postulacion y requisitos oficiales

Revision ID: 912526110570
Revises: 12d98019c3ca
Create Date: 2026-08-15 05:14:26.547681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912526110570'
down_revision: Union[str, Sequence[str], None] = '12d98019c3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Lista de postulación (varias carreras) y requisitos oficiales.

    Tres cuidados sobre datos que ya existen:

    1. `preferencia` es NOT NULL y la tabla tiene filas: se crea con un valor
       por defecto y recién después se quita el default, para no romper.
    2. NEM y ranking se MUEVEN de la postulación al usuario. Se copian antes de
       borrar las columnas: son datos que el estudiante escribió a mano y
       perderlos por una refactorización sería imperdonable.
    3. El unique de `user_id` se cambia por uno compuesto: antes solo se podía
       tener una meta, ahora se pueden tener diez.
    """
    op.add_column("carreras", sa.Column("ponderado_min", sa.Float(), nullable=True))
    op.add_column("carreras", sa.Column("promedio_min", sa.Float(), nullable=True))
    op.add_column("carreras", sa.Column("vacantes", sa.Integer(), nullable=True))

    op.add_column("users", sa.Column("puntaje_nem", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("puntaje_ranking", sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE users
        SET puntaje_nem = g.puntaje_nem,
            puntaje_ranking = g.puntaje_ranking
        FROM user_goals g
        WHERE g.user_id = users.id
        """
    )

    op.add_column(
        "user_goals",
        sa.Column("preferencia", sa.Integer(), nullable=False, server_default="1"),
    )
    op.alter_column("user_goals", "preferencia", server_default=None)

    op.drop_index(op.f("ix_user_goals_user_id"), table_name="user_goals")
    op.create_index(op.f("ix_user_goals_user_id"), "user_goals", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_meta_usuario_carrera", "user_goals", ["user_id", "carrera_id"]
    )

    op.drop_column("user_goals", "puntaje_ranking")
    op.drop_column("user_goals", "puntaje_nem")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'puntaje_ranking')
    op.drop_column('users', 'puntaje_nem')
    op.add_column('user_goals', sa.Column('puntaje_nem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_goals', sa.Column('puntaje_ranking', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_meta_usuario_carrera', 'user_goals', type_='unique')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=True)
    op.drop_column('user_goals', 'preferencia')
    op.drop_column('carreras', 'vacantes')
    op.drop_column('carreras', 'promedio_min')
    op.drop_column('carreras', 'ponderado_min')
    # ### end Alembic commands ###
