"""recordatorios por correo

Revision ID: 9ba90decdcbf
Revises: 912526110570
Create Date: 2026-08-15 15:28:14.396587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba90decdcbf'
down_revision: Union[str, Sequence[str], None] = '912526110570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Preferencia de recordatorios, activada por defecto.

    `server_default` porque la tabla ya tiene usuarios: sin él, la columna NOT
    NULL falla sobre las filas existentes. Se activa para todos porque es el
    comportamiento que el estudiante espera al registrarse en una plataforma de
    estudio — y porque cada correo lleva su enlace para apagarlo en un clic.
    """
    op.add_column(
        "users",
        sa.Column(
            "recordatorios_email", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    op.add_column(
        "users",
        sa.Column("ultimo_recordatorio", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ultimo_recordatorio')
    op.drop_column('users', 'recordatorios_email')
    # ### end Alembic commands ###
