"""cuestionario de bienvenida

Revision ID: aaa80efc2917
Revises: 80ac40c7905a
Create Date: 2026-08-15 16:20:26.669728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa80efc2917'
down_revision: Union[str, Sequence[str], None] = '80ac40c7905a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pruebas_objetivo', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('curso', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('primera_vez', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('puntaje_anterior', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('horas_semana', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('onboarding_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_at')
    op.drop_column('users', 'horas_semana')
    op.drop_column('users', 'puntaje_anterior')
    op.drop_column('users', 'primera_vez')
    op.drop_column('users', 'curso')
    op.drop_column('users', 'pruebas_objetivo')
    # ### end Alembic commands ###
