"""visitas: dispositivo, sistema y navegador en categorias gruesas

Revision ID: f51fd8590bb7
Revises: aaa80efc2917
Create Date: 2026-08-15 20:15:39.521553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51fd8590bb7'
down_revision: Union[str, Sequence[str], None] = 'aaa80efc2917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_views', sa.Column('device', sa.String(length=20), nullable=True))
    op.add_column('page_views', sa.Column('os', sa.String(length=20), nullable=True))
    op.add_column('page_views', sa.Column('browser', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_views', 'browser')
    op.drop_column('page_views', 'os')
    op.drop_column('page_views', 'device')
    # ### end Alembic commands ###
